name: Mcmmorankup
main: me.stutiguias.mcmmorankup.Mcmmorankup
version: 0.5
author: Stutiguias
depend: [Vault,mcMMO]
commands:
  mru:
   description: Check your Rank
   usage:
   
permissions:
    mru.hability:
       description: Give Acess to Skill By Hability
       default: true
    mru.reload:
       description: reload the plugin
       default: op