name: Mcmmorankup
main: me.stutiguias.mcmmorankup.Mcmmorankup
version: 0.4-SNAPSHOT
author: Stutiguias
depend: [Vault,mcMMO]
commands:
  mru:
   description: Check your Rank
   usage: /mru check
   
permissions:
    